POST http://localhost:7071/api/queuework HTTP/1.1
content-type: application/json

{
    "name" : "My important work 01",
    "isComplete" : false
}

###
GET http://localhost:7071/api/status/854aeea1a3334cc6beb94eabf92bf06c HTTP/1.1