###
GET http://localhost:5000/todoworkitems HTTP/1.1
###
GET http://localhost:5000/ HTTP/1.1
###
POST http://localhost:5000/todoworkitems HTTP/1.1
content-type: application/json

{
    "name" : "Important work 02",
    "isComplete" : false
}


###
PUT http://localhost:5000/todoworkitems/1 HTTP/1.1
content-type: application/json

{
    "name" : "Important work 01 - completed",
    "isComplete" : true
}

###
GET http://localhost:5000/status